localStorageBranchTargets:
  features/config/US-68040-NEW: integration
  features/config/US-68040-AlertObject: integration
  features/config/US-68040-LWC: integration
  features/config/US-68040-ToastNew: integration
  features/config/US-Hotfix-AppAssignment: integration
  features/config/US-Hotfix-AlertFlow: integration
  features/config/US-Hotfix-Alertflowv2: integration
  features/config/US-Hotfix-TaskTranslationReset: integration
  features/config/US-69987-BugfixQuickChoice: integration
  features/config/US-69987-BugFixQuickChoiceV2: integration
  features/config/US-Branding: integration
  features/config/US-BugfixesContact: integration
  features/config/US-AccountFlexiPage: integration
  features/config/US-BUGFIX-ORGCHARTFLOWS: integration
  features/config/US-71428-FindingsAnnelies: integration
  features/config/US-71338-FeedbackAccountEM: integration
  features/config/US-71338-AccountFlexiPageChanges: integration
  features/config/US-Hotfix-PMsetsadminuser: integration
  features/config/US-Hotfix-AccountFlexiPage: integration
  features/config/US-Subsector: integration
  features/config/US-ThemeObject: integration
  features/config/US-72003-LoginPage: integration
  features/config/US-72315-TaskType: integration
  features/config/US-72315-Task-Layout-and-Global: integration
scratchOrgAlias: null
scratchOrgUsername: null
installedApps:
  - git
sfdxPluginsStdout: "packaging \e[2m1.27.1\e[22m\nsfdmu \e[2m4.30.0\e[22m\nsfdx-essentials \e[2m2.12.0\e[22m\nsfdx-git-delta \e[2m5.27.0\e[22m\nsfdx-hardis \e[2m4.10.1\e[22m\ntexei-sfdx-plugin \e[2m2.1.3\e[22m\n\e[2m\e[22m\n\e[2mUninstalled JIT Plugins:\e[22m\ncommunity \e[2m2.4.2\e[22m\ncustom-metadata \e[2m2.2.2\e[22m\ndev \e[2m1.2.0\e[22m\ndevops-center \e[2m1.2.0\e[22m\nenv \e[2m2.2.1\e[22m\nfunctions \e[2m1.22.3\e[22m\nsignups \e[2m1.5.0\e[22m\n@salesforce/sfdx-plugin-lwc-test \e[2m1.1.0\e[22m\n@salesforce/sfdx-scanner \e[2m3.16.0\e[22m\n"
mergeRequests:
  - null
  - branch: features/config/US-ThemeObject
