localStorageBranchTargets:
  features/config/auth-orgs-cicd: integration
  features/config/full-copy-of-created-features: integration
  features/config/US-69013: integration
  features/config/sprint-1-additional-components: integration
  features/config/hot-fixes-from-demo: integration
  features/config/US-69987: integration
  features/config/us-wesley: integration
scratchOrgAlias: null
scratchOrgUsername: null
installedApps:
  - git
  - openssl
userEmail: wesley.bik@brightfox.eu
sfdxPluginsStdout: "functions \e[2m1.22.3\e[22m\e[2m (1.22.3)\e[22m\npackaging \e[2m1.26.4\e[22m\nsfdmu \e[2m4.30.0\e[22m\nsfdx-essentials \e[2m2.12.0\e[22m\nsfdx-git-delta \e[2m5.27.0\e[22m\nsfdx-hardis \e[2m4.7.0\e[22m\ntexei-sfdx-plugin \e[2m2.1.3\e[22m\n\e[2m\e[22m\n\e[2mUninstalled JIT Plugins:\e[22m\ncommunity \e[2m2.4.5\e[22m\ncustom-metadata \e[2m2.2.6\e[22m\ndev \e[2m1.2.0\e[22m\ndevops-center \e[2m1.2.2\e[22m\nenv \e[2m2.2.4\e[22m\nsignups \e[2m1.5.3\e[22m\n@salesforce/sfdx-plugin-lwc-test \e[2m1.1.0\e[22m\n@salesforce/sfdx-scanner \e[2m3.17.0\e[22m\n"
mergeRequests:
  - branch: features/config/sprint-1-additional-components
  - branch: features/config/US-69987
    urlCreate: >-
      https://github.com/JowinWaaijer/heijmans-infra/pull/new/features/config/US-69987
