developmentBranch: integration
autoCleanTypes:
  - destructivechanges
deploymentPlan:
  packages:
    - label: Deploy SharingRules - Gespreksverslag__c
      packageXmlFile: manifest/splits/packageXmlSharingRulesGespreksverslag__c.xml
      order: 30
      waitAfter: 30
